### ISSUE TITLE
This app is totally broken 

### ISSUE THREAD

**Issue by adardesign** [garann/template-chooser#10] opened 2012-06-28 13:06 UTC
After choosing something and changing a later or previous selection it doesn't update as it should

**Comment by garann** [comment] 2012-06-28 14:43
Totally broken? Oh no. Do you think there's any point in trying to fix it, or should I just voluntarily exile myself to a new career as a carrot farmer in Uruguay? If you think there's a chance some crumb of usefulness can be chipped from the facade of frustrating impotence, maybe you could tell me a little more about what isn't updating and what your environment looks like?

**Comment by adardesign** [comment] 2012-06-29 14:14
first, sorry for calling it totaly broken.

Sure, ill try to explain you what happened, (wish i can screencast it)

Using chrome canary (Version 20.0.1132.43) // maybe thats why i had this expireince.

When i choose the first option (client or server) from the series of questions it behaves as expected, it narrowed down the list of templates according to my selction, great!

All seems to be working fine.

But when i then go to the 3rd question,  it hides all of the templates, but now even if i go back and change the first and or the second question, it still has "all templlates" hidden.

Thanx anyway

**Comment by garann** [comment] 2012-06-29 15:04
You can call it totally broken or anything else you like, as long as you explain what needs to be fixed. :)

What you're describing sounds like a problem I'm aware of, but haven't yet fixed. The tool works as a process of elimination, but there's no way to un-set a given option, taking it out of the equation. I'll comment again when I add that in, and hopefully it will work for you at that point. Thanks for explaining!

**Comment by adardesign** [comment] 2012-06-29 16:01
Thanks much!

On Fri, Jun 29, 2012 at 11:04 AM, Garann Means <
reply@reply.github.com

**Comment by ravi** [comment] 2013-02-19 04:57
Garann, the tool is actually enormously useful -- I did not even know about Transparency until I used the tool! But the issue is a bit larger than unsetting a choice. Even flipping a choice in a particular way causes somewhat erratic behaviour (that can be cleared by reloading the page). E.g: leave everything else as-is, and open the DOM structure question and select DOM. Now click on DOM again. Then click on String. The choices go blank. Clicking some number of times on String brings the relevant choices back into view, and/or clicking back on DOM followed by String in a sequence of clicks returns the correct values. I haven't had the time to figure out the algorithm to induce the right behaviour once the strangeness starts, nor have I had a chance to look at your code to see what could be causing this. I would like to do the latter though, in case I can submit a patch/pull. In the meantime, documenting my finding here. Thank you for the tool itself. Very helpful.

**Comment by xixixao** [comment] 2013-02-23 16:58
I confirm ravi's findings, on FF18. The tool looks great though, thanks .)

**Comment by garann** [comment] 2013-02-24 18:41
@ravi - thanks for the steps to reproduce! Should be fixed now.

**Comment by ravi** [comment] 2013-02-27 03:51
@garann looks good, I cannot reproduce the problem any longer. Thank you for the fix.

**Closed as completed** 2013-06-06 02:40 UTC
